@startuml
掌柜 -> api as "boss-api": 1.获取首页数据
api -> api : 2.判断商圈是否使用ERP
alt 不使用ERP
    api -> api:
    note right
      功能不变
    end note
else 使用ERP
    api -> mis as "mis-center-soa": 3.获取数据
    alt 4.获取店铺列表
        mis -> mis:
         mis -> shop as "shop-soa" : 4.1.获取店铺列表（时间范围+mallId）
         shop -> mis: 4.2.返回店铺列表（进行缓存）
         mis -> mis: 4.3.获取过滤后的店铺(进行缓存)
         note right
            1.用户可管理的【楼层+业态】
            2.不是统收台店铺
         end note
    end
    mis -> data as "data-lake-soa": 5.获取数据【H+1,T+1】参数：(时间范围，门店列表)
    data -> mis: 6.返回数据
    mis -> api: 7.返回数据
end
api -> 掌柜 : 8. 返回结果
@enduml
