@startuml
掌柜 -> api as "boss-api": 1.获取首页数据
api -> api : 2.判断商圈是否使用ERP
alt 不使用ERP
    api -> api:
    note right
      功能不变
    end note
else 使用ERP
    api -> mis as "mis-center-soa": 3.获取数据
    alt 获取店铺列表
         mis -> shop as "shop-soa" : 4.获取店铺列表（时间范围+mallEntityId）
         shop -> mis: 5.返回店铺列表（进行缓存）
         mis -> bps as "bps-soa": 6.获取用户可管理的楼层业态
         bps -> mis:7.返回权限列表
         mis -> mis: 8.获取过滤后的店铺(进行缓存)
         note right
            1.用户可管理的
            2.不是统收台店铺
         end note
    end
    mis -> data as "data-lake-soa": 9.获取数据【H+1,T+1】参数：(时间范围，门店列表)
    data -> mis: 10.返回数据
    mis -> api: 11.返回数据
end
api -> 掌柜 : 12. 返回结果
@enduml
